export const STAR_RATINGS = [
  { value: 0, element: null, label: "Tất cả Sao" },
  { value: 1, element: "ONE_STAR", label: "⭐ (ONE_STAR)" },
  { value: 2, element: "TWO_STAR", label: "⭐⭐ (TWO_STAR)" },
  { value: 3, element: "THREE_STAR", label: "⭐⭐⭐ (THREE_STAR)" },
  { value: 4, element: "FOUR_STAR", label: "⭐⭐⭐⭐ (FOUR_STAR)" },
  { value: 5, element: "FIVE_STAR", label: "⭐⭐⭐⭐⭐ (FIVE_STAR)" },
];

export const VIETNAM_PROVINCES = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bạc Liêu",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cần Thơ",
  "Cao Bằng",
  "Đà Nẵng",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];

export const RoomStatus = {
  AVAILABLE: "AVAILABLE",
  BOOKED: "BOOKED",
  MAINTENANCE: "MAINTENANCE",
};

export const RoomType = {
  STANDARD: "STANDARD",
  DELUXE: "DELUXE",
  SUITE: "SUITE",
  FAMILY: "FAMILY",
};
